# Placeholders
#----------------------------------------------------------------
#
# Placeholders for [Command Logger]
# %player% - Player Name
# %command% - Command it will log
# %server% - pulls from the config option "server_name"
# %time% - Place holder for how many Seconds/Mins/Hours/Days command was ago
#
# Plugin Created by DankOfUK with help from ChatGPT
# Discord for Support: http://discord.gg/2xYgHUfubM


#----------------------------------------------------------------
# Discord Bot Settings
#----------------------------------------------------------------
bot:
  # Main Bot Configuration
  enabled: true # Enable if you want to use the [Command Logger, List Players, Discord Bot and more]
  discord_token: "" # Discord Bot Token
  adminRoleID: "1057520326373801995" # Role ID for admin commands
  discord_activity: "with KushStaffUtils"

  #----------------------------------------------------------------
  # Log Command Configuration
  #----------------------------------------------------------------
  logsCommand_requireAdminRole: true

  #----------------------------------------------------------------
  # Discord Chat 2 Game Chat Configuration
  #----------------------------------------------------------------
  discord_to_game_enabled: true
  discord_to_game_roleIdRequired: false
  discord_to_game_roleId: "967958848369487943" #This is if roleIdRequired is true
  discord_to_game_channel_id: "1067570285999570984"
  discord_to_game_format: "&9[Discord] &c%author%: &7%message%"

  #----------------------------------------------------------------
  # List Players Configuration
  #----------------------------------------------------------------
  listplayers_requireAdminRole: false
  listplayers_no_players_online_title: "`Online Players`"
  listplayers_title_format: "Players Online `(%online%)` - %time%"
  listplayers_footer_format: "Server IP: play.example.com - Test"
  listplayers_thumbnail_url: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=1024"

#----------------------------------------------------------------
# Server Shutdown/Startup Logger Configuration - WOIP
#----------------------------------------------------------------
serverstatus:
  channel_id: "1096952523585245195"

#----------------------------------------------------------------
# Enable this if you want it to log commands to a file per use! (STORED VIA UUIDS)
#----------------------------------------------------------------
per-user-logging:
  enabled: true # this logs in KushStaffLogger/logs

#----------------------------------------------------------------
# Factions Top Announcer
#----------------------------------------------------------------
announcer:
  enabled: false
  webhookUrl: "your-webhook-here"
  sendEvery: 15
  title: "Factions Top Announcement"
  username: "FactionsBot"
  footer: "Factions Top Logger"
  messages:
    - "Factions Top #1: %factionstop_ftop1% - `$%factionstop_ftop1-totalworth%`"
    - "Factions Top #2: %factionstop_ftop2% - `$%factionstop_ftop2-totalworth%`"
    - "Factions Top #3: %factionstop_ftop3% - `$%factionstop_ftop3-totalworth%`"
    - "Factions Top #4: %factionstop_ftop4% - `$%factionstop_ftop4-totalworth%`"
    - "Factions Top #5: %factionstop_ftop5% - `$%factionstop_ftop5-totalworth%`"
    - "Factions Top #6: %factionstop_ftop6% - `$%factionstop_ftop6-totalworth%`"
    - "Factions Top #7: %factionstop_ftop7% - `$%factionstop_ftop7-totalworth%`"
    - "Factions Top #8: %factionstop_ftop8% - `$%factionstop_ftop8-totalworth%`"
    - "Factions Top #9: %factionstop_ftop9% - `$%factionstop_ftop9-totalworth%`"
    - "Factions Top #10: %factionstop_ftop10% - `$%factionstop_ftop10-totalworth%`"
    - ""
    - "Join our server to compete!"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"
  avatarUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"
  debuggerEnabled: false #Only enabled if debugging is required


#----------------------------------------------------------------
# Command Logger Configuration
#----------------------------------------------------------------
commandlogger:
  # Message format for the message.
  message_formats:
    - "\n:information_source: __**Player:**__\n> `%player%`\n \n:gear: __**Use Commands:**__\n> `%command%`\n \n:satellite: __**Server:**__\n> `%server%`\n \n:timer: __**Time:**__\n> %time%"
  # Title Format for the message.
  title_formats:
    - ":information_source: COMMAND LOGGER"
  author_message: "%player%"
  # If enabled it will send as an embed message!
  logAsEmbed: true
  # Channel ID for the logging channel
  channel_id: "CHANNEL_ID_HERE"
  # Gets the Server Name for the %server% placeholder
  server_name: "Example Server"

  #----------------------------------------------------------------
  # Command Logger Whitelist Mode Configuration
  #----------------------------------------------------------------
  # If false it will log all commands (ignored_commands wont ever be logged)
  # If true it will only log the command in the whitelist_commands (ignored_commands wont ever be logged)
  whitelist_mode_enabled: false
  # Commands the will be logged if set to true (ignored_commands wont ever be logged)
  whitelisted_commands:
    - "/ipmute"
    - "/ipban"
    - "/kill"

  # Commands the command logger will never log
  ignored_commands:
    - "/pin"
    - "/register"
    - "/login"
    - "/password"

#----------------------------------------------------------------
# Messages Config
#----------------------------------------------------------------
# Change the no permission message!
no_permission: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYou do not have permission to &c/stafflogger&f!"

# Change the no permission message!
reload_message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fThe config files have been reloaded!"

#----------------------------------------------------------------
# Chat Webhook Configuration
#----------------------------------------------------------------
chatwebhook:
  enabled: false
  url: "your-webhook-here"
  username: "My Bot Username"
  avatarUrl: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  message: "[%vault_groups% %player_name%]: %message%"

#----------------------------------------------------------------
# Strike Command Configuration
#----------------------------------------------------------------
strike:
  enabled: true
  webhookUrl: "https://discord.com/api/webhooks/1146845972815695902/Z-PyVSYmCMkA6if2u1cVJwLOuZC0EvouL8Oo5PlMBg2b9u5UvJfMKxZy-4pkrdEOlTgJ"
  username: "FactionStrikeBot"
  avatarUrl: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  embedTitle: ":book: `Faction Strike`"
  message: ":information_source: `Faction:`\n> **%group%**\n \n:red_circle: `Amount of Strikes:`\n> **%amount%**\n \n:books: `Reason:`\n> %reason%\n \n:man_beard: `Striked by:`\n> %staff%"
  thumbnail: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  staffMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYou have given &c%group% %amount% &aof strikes for &c%reason%"
  sendCommand:
    - "me test"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /strike <group> <amount> <reason>"

#----------------------------------------------------------------
# Bug Report Command Configuration
#----------------------------------------------------------------
bug_report:
  enabled: true # Set this to true to enable the /strike command
  webhookUrl: "https://discord.com/api/webhooks/1146845972815695902/Z-PyVSYmCMkA6if2u1cVJwLOuZC0EvouL8Oo5PlMBg2b9u5UvJfMKxZy-4pkrdEOlTgJ"
  thumbnailUrl: "https://example.com/your-thumbnail-url"
  cooldown: 60 # Cooldown time in seconds
  username: "YourBotUsername"
  avatarUrl: "https://example.com/your-avatar-url"
  message: ":information_source: `Bug Reporter:`\n> **%player%**\n \n:red_circle: `Bug Info:`\n> **%bug%**"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &c/bug <report>"
  responseMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fYour bug report has been logged.\n&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fOverview: &c%reason%"

#----------------------------------------------------------------
# Player Reporting Command Configuration
#----------------------------------------------------------------
report:
  enabled: true  # Set this to true to enable the /report command
  webhookUrl: "YOUR_WEBHOOK_URL_HERE"
  username: "ReportBot"
  avatarUrl: "YOUR_AVATAR_URL_HERE"
  message: ":information_source: `Player Reporting:`\n> **%player%**\n \n:red_circle: `Player Reported:`\n> **%reported_player%**\n \n:books: `Reason:`\n> %reason%"
  cooldown: 60  # Cooldown in seconds
  sentMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYour report has been sent!"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /report <player> <reason>"

#----------------------------------------------------------------
# Player Join/Leave Logger Configuration
#----------------------------------------------------------------
player_leave_join_logger:
  enabled: false  # Set this to true to enable player join/leave logging
  #----------------------------
  # Join Message Configuration
  #----------------------------
  joinWebhookUrl: "YOUR_JOIN_WEBHOOK_URL_HERE"
    joinMessage:
      - "> <:dot:1071609577122041856> `%player%` has *joined* the server!"
      - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
      - ""
      - "> :satellite: Server IP > play.servername.net"
      - "> :computer: Website > www.servername.net"
      - "> :department_store: Store > store.servername.net"
  #-----------------------------
  # Leave Message Configuration
  #-----------------------------
  leaveWebhookUrl: "YOUR_LEAVE_WEBHOOK_URL_HERE"
  leaveMessage:
    - "> <:dot:1071609577122041856> `%player%` has *left* the server!"
    - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
    - ""
    - "> :satellite: Server IP > play.servername.net"
    - "> :computer: Website > www.servername.net"
    - "> :department_store: Store > store.servername.net"
  #----------------------------------------------------------------
  # Message Embed Configuration - true = embeded message, false = normal message
  #----------------------------------------------------------------
  useEmbed: true  # Set this to true to use Discord embeds

#----------------------------------------------------------------
# Suggestion Command Configuration
#----------------------------------------------------------------
suggestion:
  cooldown: 60
  title: "New Suggestion from %player%"
  description: "%suggestion%"
  color: "#94157f"
  footer: "Submitted by %player% (%player_uuid%)"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=4096"
  channelId: "1146844174524612638"
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /suggest <suggestion>"
  sentMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYour suggestion (%suggestion%) has been sent!"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."