# Placeholders for Staff Logger Webhook
# %player% - Player Name
# %command% - Command it will log
# %server% - pulls from the config option "server_name"
# %time% - Place holder for how many Seconds/Mins/Hours/Days command was ago
#
# Plugin Created by DankOfUK with help from ChatGPT
# Discord for Support: http://discord.gg/2xYgHUfubM


#
# Discord Bot Settings
#
bot:
  enabled: true
  discord_token: ""
  command_prefix: "+"
  adminRoleID: "1057520326373801995"
  discord_activity: "with KushStaffUtils"

  # Command Logger Configuration
  command_log_channel_id: "1067570285999570984"
  command_log_logAsEmbed: true
  command_log_message_formats:
    - "\n:information_source: __**Player:**__\n> `%player%`\n \n:gear: __**Use Commands:**__\n> `%command%`\n \n:satellite: __**Server:**__\n> `%server%`\n \n:timer: __**Time:**__\n> %time%"
  command_log_embed_title_formats:
    - ":information_source: COMMAND LOGGER"

  # Discord Chat 2 Game Chat
  discord_to_game_enabled: true
  discord_to_game_roleIdRequired: true
  discord_to_game_roleId: "967958848369487943" #This is if roleIdRequired is true
  discord_to_game_channel_id: "1067570285999570984"
  discord_to_game_format: "&9[Discord] &c%author%: &7%message%"

  # List Players

  listplayers_title_format: "Online (%online%)"
  listplayers_footer_format: "Online (%online%)"
  listplayers_thumbnail_url: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=1024"

# Server Shutdown/Startup Logger
serverstatus:
  channel_id: "1096952523585245195"

# Enable this if you want it to log commands to a file per use! (STORED VIA UUIDS)
log_commands: true # this logs in KushStaffLogger/logs


suggestion:
  title: "New Suggestion from %player%"
  description: "%suggestion%"
  color: "#94157f"
  footer: "Submitted by %player% (%player_uuid%)"
  thumbnail_url: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=4096"
  channel_id: "1096952523585245195"
  thread_id: "1096952523585245195" #Coming Soon
  usage_message: "&cUsage: /suggest <suggestion>"
  sent_message: "&aYour suggestion (%suggestion%) has been sent!"
  cooldown: 60



# Player Reporting Configuration
enabled: true # If disabled it will not work
# Chat Reporting Webhook Lang
webhook-url: "https://discord.com/api/webhooks/1101921122993315960/_7MP0KWNdhlJVXLi02LUCdfuL0YB5XXkC26NvhArDuGJ-mcSBdDxe2kVlmYuzSqf5F-I"
username: "OBN"
avatar-url: "https://example.com/avatar.png"
report-message: ":information_source: `Player Reporting:`\n> **%player%**\n \n:red_circle: `Player Reported:`\n> **%reported_player%**\n \n:books: `Reason:`\n> %reason%"
# Chat Reporting Lang
cooldown-seconds: 15 # seconds
report-sent-message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYour report has been sent!\n&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fThank you for helping us make the server safer!"
no-permission-message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYou do not have permission to use this command."
usage-message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &c/report <player> <reason>\n&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fPlease use &cImgur&f or &cYoutube&f for proof."



# Join Leave Webhooks Logger
isEnabled: false
joinWebhookUrl: "https://discord.com/api/webhooks/1090091527742689280/2EWe1JJ3R-e5dkVcugE-4gdepyRhMkH0d1yLIBfNNA-ZH9Dwmx8oPREQwgzQ4v_dIeLk"
leaveWebhookUrl: "https://discord.com/api/webhooks/1090710491367743560/pGxPya19ypXpM886o7zBTWeHvlC3G8ziuE07nEUixKYm734GAXwxuZnHFO3u0HIbUuLl"
# Join and leave messages (THESE ARE SEND WHEN A PLAYER JOINS OR LEAVES THE SERVER)
joinMessage:
  - "> <:dot:1071609577122041856> `%player%` has *joined* the server!"
  - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
  - ""
  - "> :satellite: Server IP > play.servername.net"
  - "> :computer: Website > www.servername.net"
  - "> :department_store: Store > store.servername.net"
leaveMessage:
  - "> <:dot:1071609577122041856> `%player%` has *left* the server!"
  - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
  - ""
  - "> :satellite: Server IP > play.servername.net"
  - "> :computer: Website > www.servername.net"
  - "> :department_store: Store > store.servername.net"
# If enabled it will send as a embed message!
useEmbed: true
# Gets the Server Name for the %server% placeholder
server_name: "ONEBLOCK NATION"



# Reload Config Config
#
# Change the no permission message!
no_permission: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYou do not have permission to &c/stafflogger&f!"

# Change the no permission message!
reload_message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fThe config files have been reloaded!"

# Commands the plugin will ingore
ignored_commands:
  - "/pin"
  - "/register"
  - "/login"
  - "/password"

# If false it will log all commands (ignored_commands wont ever be logged)
# If true it will only log the command in the whitelist_commands (ignored_commands wont ever be logged)
whitelist_enabled: false
# Commands the will be logged if set to true (ignored_commands wont ever be logged)
whitelisted_commands:
  - "/kick"
  - "/ipmute"
  - "/ipban"
  - "/ban"
  - "/tempban"
  - "/mute"
  - "/tempmute"
  - "/warn"
  - "/clearchat"
  - "/gmc"
  - "/gmsp"
  - "/co i"
  - "/co rollback"
  - "/co"
  - "/irp restore"
  - "/irp"
  - "/invsee"
  - "/kill"

# Configuration file for Log Viewer - COMING SOON
#logs-header: "&6=== &e%player% Logs &6=== &ePage &f%currentPage%&e/&f%maxPage% &6==="
#prev-page: "&a<< Previous Page"
#next-page: "&aNext Page >>"
#page_size: 15

# Chat Webhook - BETA (LOGS GAME CHAT TO DISCORD)
chatwebhook:
  enabled: false
  url: "YOUR-WEBHOOK-HERE"
  serverName: "My Server Name"
  username: "My Bot Username"
  avatarUrl: "https://example.com/avatar.png"
  message: "[%vault_groups% %player_name%]: %message%"

# Configure StrikeWebhook
strike:
  enabled: true
  webhookUrl: "YOUR-WEBHOOK-HERE"
  username: "FactionStrikeBot"
  avatarUrl: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  embedTitle: ":book: `Faction Strike`"
  staffMessage: "&aYou have given &c%group% %amount% &aof strikes for &c%reason%"
  message: ":information_source: `Faction:`\n> **%group%**\n \n:red_circle: `Amount of Strikes:`\n> **%amount%**\n \n:books: `Reason:`\n> %reason%"
  thumbnail: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  sendCommand: "f strike add %group% %amount%"
  noPermissionMessage: "&cYou do not have permission to use this command."
  usageMessage: "&cUsage: /strike <group> <amount> <reason>"

# Factions Top Announcer
announcer:
  webhookUrl: "https://discord.com/api/webhooks/1067580388412764191/mEuoDytO56R4D7aWu9ubb1qmYxjlPCYIqbKV52T-rGALteWG18kF5lUgfAfCqan-WySp"
  messages:
    - "Factions Top #1: %factionstop_ftop1% - `$%factionstop_ftop1-totalworth%`"
    - "Factions Top #2: %factionstop_ftop2% - `$%factionstop_ftop2-totalworth%`"
    - "Factions Top #3: %factionstop_ftop3% - `$%factionstop_ftop3-totalworth%`"
    - "Factions Top #4: %factionstop_ftop4% - `$%factionstop_ftop4-totalworth%`"
    - "Factions Top #5: %factionstop_ftop5% - `$%factionstop_ftop5-totalworth%`"
    - "Factions Top #6: %factionstop_ftop6% - `$%factionstop_ftop6-totalworth%`"
    - "Factions Top #7: %factionstop_ftop7% - `$%factionstop_ftop7-totalworth%`"
    - "Factions Top #8: %factionstop_ftop8% - `$%factionstop_ftop8-totalworth%`"
    - "Factions Top #9: %factionstop_ftop9% - `$%factionstop_ftop9-totalworth%`"
    - "Factions Top #10: %factionstop_ftop10% - `$%factionstop_ftop10-totalworth%`"
    - ""
    - "Join our server to compete!"
  sendEvery: 60 #in seconds
  enabled: false
  title: "Factions Top Announcement"
  username: "FactionsBot"
  footer: "Factions Top Logger"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"
  avatarUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"


# Bug Command Webhook
bug_webhook_url: ""
bug_username: "BUG REPORT"
bug_thumbnail: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
bug_avatar_url: "https://example.com/bug-avatar.png"
is_bug_enabled: true
bug_cooldown: 30
bug_message: ":information_source: `Bug Reporter:`\n> **%player%**\n \n:red_circle: `Bug Info:`\n> **%bug%**"
no_bug_permission_message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYou do not have permission to use this command."
bug_usage_message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &c/bug <report>"
bug_sent_message: "&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fYour bug report has been logged.\n&c[&c&lsᴜᴘᴘᴏʀᴛ&c] &8» &fOverview: &c%reason%"

# Enderpearl Cooldown Configuration
enderpearl:
  enabled: false
  cooldown-time: 10
  cooldown-message: '&cYou must wait %time_left% seconds before using this again!'
# Chorus Fruit Cooldown Configuration (DO NOT ENABLE IF YOUR BELOW 1.9+)
chorus:
  enabled: false # (DO NOT ENABLE IF YOUR BELOW 1.9+)
  cooldown-time: 10 # (DO NOT ENABLE IF YOUR BELOW 1.9+)
  cooldown-message: '&cYou must wait %time_left% seconds before using this again!' # (DO NOT ENABLE IF YOUR BELOW 1.9+)