name: KushStaffUtils
version: '${project.version}'
main: me.dankofuk.KushStaffUtils
author: DankOfUK
description: Made by Exotic Development
load-after: [InteractiveChat, AntiCheatReplay, LiteBans, AdvancedBans]
softdepend: [PlaceholderAPI, Vault, AntiCheatReplay, LiteBans, AdvancedBans]
commands:
  stafflogger:
    description: reloads the config.
    usage: /stafflogger reload - Reloads the config
  viewlogs:
    description: views a players command logs ingame
    usage: /viewlogs <player_name> - Views a players command logs
  report:
    description: reports a player ingame
  bug:
    description: report a bug to the developers
  strike:
    description: strike a group, island, faction
    aliases: [strikes]
  suggestion:
    description: Make a suggestion
    aliases: [suggest]
